// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjECCHoHUz7K-XerjCG-yeM4kDDcbf8hg',
    appId: '1:761925234385:web:bc5cd3804419a7cdad5ff0',
    messagingSenderId: '761925234385',
    projectId: 'my-baby-app-dev',
    authDomain: 'my-baby-app-dev.firebaseapp.com',
    storageBucket: 'my-baby-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl5APQmrpY4zG3CEbSVy80KZ4yi5HYaEA',
    appId: '1:761925234385:android:b1c794a7acd280fbad5ff0',
    messagingSenderId: '761925234385',
    projectId: 'my-baby-app-dev',
    storageBucket: 'my-baby-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC353UgvQQ41NqRYP1XYlXRI2YwjgF-csA',
    appId: '1:761925234385:ios:cbcfb9307a4592d9ad5ff0',
    messagingSenderId: '761925234385',
    projectId: 'my-baby-app-dev',
    storageBucket: 'my-baby-app-dev.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC353UgvQQ41NqRYP1XYlXRI2YwjgF-csA',
    appId: '1:761925234385:ios:cbcfb9307a4592d9ad5ff0',
    messagingSenderId: '761925234385',
    projectId: 'my-baby-app-dev',
    storageBucket: 'my-baby-app-dev.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjECCHoHUz7K-XerjCG-yeM4kDDcbf8hg',
    appId: '1:761925234385:web:5b79d8e45ad6029aad5ff0',
    messagingSenderId: '761925234385',
    projectId: 'my-baby-app-dev',
    authDomain: 'my-baby-app-dev.firebaseapp.com',
    storageBucket: 'my-baby-app-dev.firebasestorage.app',
  );
}
